name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu"]
        jvm: ["17", "21", "25"]
        scala: ["2.12.x", "3.x"]
        include:
          - os: windows
            jvm: 8
            scala: 2.12.x
          - os: windows
            jvm: 17
            scala: 3.x
          - os: ubuntu
            jvm: 8
            scala: 2.12.x
          - os: ubuntu
            jvm: 11
            scala: 2.12.x
    name: ${{ matrix.os }} / JDK ${{ matrix.jvm }} / Scala ${{ matrix.scala }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v6
      - uses: coursier/setup-action@v2
        with:
          apps: sbt
          jvm: temurin:${{ matrix.jvm }}
      - if: matrix.jvm == '8' || matrix.jvm == '11' || matrix.jvm == '17'
        run: rm -r src/sbt-test/skip-sbt1.4
      - if: matrix.jvm == '17' || matrix.jvm == '21' || matrix.jvm == '25'
        run: rm -r src/sbt-test/skip-java17+
      - if: matrix.os == 'windows'
        run: rm -r src/sbt-test/skip-windows
      - run: sbt ++${{ matrix.scala }} test scripted
  formatting:
    name: Scalafmt and Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: coursier/setup-action@v2
        with:
          apps: sbt
      - run: ./bin/scalafmt --test
      - run: sbt "scalafixAll --check"
